name: riyadh_kmcc_new
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cached_network_image: ^3.4.0
  device_preview: ^1.1.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets: 
    - assets/
    - assets/icons/

  fonts:
      - family: SfProMedium
        fonts:
          - asset: assets/fonts/SF-Pro-Display-Medium.otf
      - family: SfProBold
        fonts:
          - asset: assets/fonts/SFPRODISPLAYBOLD.OTF
      - family: SfProRegular
        fonts:
          - asset: assets/fonts/SFPRODISPLAYREGULAR.OTF